<?php
global $MESS;

$MESS["SALE_RBKMONEY_SHOULD_PAY"] = "Amount to be paid";
$MESS["SALE_RBKMONEY_DESCRIPTION_SHOULD_PAY"] = "";

$MESS["SALE_RBKMONEY_ORDER_ID"] = "Order ID";
$MESS["SALE_RBKMONEY_DESCRIPTION_ORDER_ID"] = "Order ID from your Internet store";

$MESS["SALE_RBKMONEY_FORM_PATH_IMG_LOGO"] = "The path to the image of the store logo displayed in the payment form";
$MESS["SALE_RBKMONEY_DESCRIPTION_FORM_PATH_IMG_LOGO"] = "";

$MESS["SALE_RBKMONEY_FORM_COMPANY_NAME"] = "Company name displayed in the payment form";
$MESS["SALE_RBKMONEY_DESCRIPTION_FORM_COMPANY_NAME"] = "";

$MESS["SALE_RBKMONEY_MERCHANT_PRIVATE_KEY"] = "Private key for payment";
$MESS["SALE_RBKMONEY_DESCRIPTION_MERCHANT_PRIVATE_KEY"] = "";

$MESS["SALE_RBKMONEY_MERCHANT_CALLBACK_PUBLIC_KEY"] = "Public key to authorize payment status notifications";
$MESS["SALE_RBKMONEY_DESCRIPTION_MERCHANT_CALLBACK_PUBLIC_KEY"] = "";

$MESS["SALE_RBKMONEY_SHOP_ID"] = "Shop ID in RBK Money";
$MESS["SALE_RBKMONEY_DESCRIPTION_SHOP_ID"] = "";

$MESS["SALE_RBKMONEY_CURRENCY"] = "Currency";
$MESS["SALE_RBKMONEY_DESCRIPTION_CURRENCY"] = "";

?>
